# Generated by Django 4.1.7 on 2023-06-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=10)),
                ('sclass', models.CharField(max_length=5)),
                ('saddr', models.CharField(max_length=20)),
            ],
        ),
    ]
