# Generated by Django 4.1.7 on 2023-06-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studen',
            new_name='student',
        ),
    ]
