# Generated by Django 4.1.7 on 2023-06-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_rename_studen_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sclass',
            field=models.IntegerField(),
        ),
    ]
